# Copy pipeline-secrets-example.yml to pipeline-secrets.yml and update with your values then run:
# fly -t ci set-pipeline -p maven-cf-simple -c pipeline.yml -l pipeline-secrets.yml
---


resources:
- name: source-code
  type: git
  source:
    skip_ssl_verification: true
    skip_cert_verification: true
    repo: vipinvkmenon/concourse-maven-cf-simple
    base: 3-sim

jobs:
- name: build
  public: true
  plan:
  - { get: source-code, trigger: true, version: every }
  - task: build
    file: source-code/ci/build.yml
  - task: verify
    file: source-code/ci/verify.yml

