# Copy pipeline-secrets-example.yml to pipeline-secrets.yml and update with your values then run:
# fly -t ci set-pipeline -p maven-cf-simple -c pipeline.yml -l pipeline-secrets.yml
---
resource_types:
  - name: pull-request
    type: docker-image
    source:
      repository: jtarchie/pr

resources:
- name: source-code
  type: pull-request
  source:
    username: vipinvkmenon
    password: 992da09f254c521d5b4c8105f93f38dccce442a7
    skip_ssl_verification: true
    skip_cert_verification: true
    repo: vipinvkmenon/concourse-maven-cf-simple
    base: master

jobs:
- name: build
  public: true
  plan:
  - { get: source-code, trigger: true, version: every }
  - task: build
    file: source-code/ci/build.yml
    on_success:
     put: source-code
     params:
       path: source-code
       status: success
    on_failure:
     put: source-code
     params:
        path: source-code
        status: failure

